### PR TITLE
Add QtPromise 0.3.0

### PR DESCRIPTION
**Pull request by simonbrunel**

### CODE REVIEW

**Comment by cornelius** [comment]
I was a bit too fast and had to revert and readd the qtpromise manifest. The inqlude web site is generated from the inqlude-data git repo on the KDE infrastructure. They have a bit stricter checks, so they don't accept "no-reply" email addresses from GitHub, but require real email addresses.

The data should be there now. But something to consider for future patches. I would like to add a check to GitHub to report these issues already on the pull request, but need to find an elegant way of doing it plus the time to implement it.

**Comment by simonbrunel** [comment]
Thanks @cornelius. I'm not sure to understand the issue with the email address, neither what I should do or change for future versions?

**Comment by cornelius** [comment]
If you look at your commit with `git log` you should see your real email address there as author and committer. That usually simply works if you are doing your commits from the command line. When you are committing from the GitHub web UI you need to make sure that you have unchecked the "Keep my email private" checkbox in your settings, otherwise you will commit with an pseudonymous email address which won't be accepted by the KDE git server.

**Comment by simonbrunel** [comment]
I thought you were talking about the manifest file, that's why I was confused about the email address, but that makes sense now. I didn't use the GH Web UI to create that PR, my git client is configured to not leak my personal email address by using the GH private one. I will use another email next time.

**Pull request merged**
