### PR TITLE
Gitorious.org

### PR DESCRIPTION
**Pull request by ibatullin**
Gitorious.org will shut down end of May. Some projects moved to another hostings.

### CODE REVIEW

**Comment by ibatullin** [comment]
Grep output after patch:
```
./qt/qt.2010-11-09.manifest:    "vcs": "http://qt.gitorious.org/qt"
./qt/qt.2013-08-28.manifest:    "vcs": "http://qt.gitorious.org/qt"
./qtoptimization/qtoptimization.manifest:    "homepage": "https://gitorious.org/qtoptimization",
./qtoptimization/qtoptimization.manifest:    "vcs": "https://gitorious.org/qtoptimization/qtoptimization"
./qt-certificate-addon/qt-certificate-addon.2013-02-17.manifest:    "vcs": "https://gitorious.org/qt-certificate-addon"
./qt-certificate-addon/qt-certificate-addon.2013-02-17.manifest:    "source": "https://gitorious.org/qt-certificate-addon/qt-certificate-addon/archive/f807e92da99d0a770d2bf22adff8b728dab83d29.tar.gz"
./qjson/qjson.2009-12-04.manifest:    "vcs": "https://gitorious.org/qjson"
./qicstable/qicstable.manifest:    "homepage": "https://gitorious.org/qicstable/",
./qicstable/qicstable.manifest:    "download": "https://gitorious.org/qicstable/qicstable/"
./log4qt-fork/log4qt-fork.manifest:    "homepage": "https://gitorious.org/log4qt/",
./log4qt-fork/log4qt-fork.manifest:    "vcs": "https://gitorious.org/log4qt/log4qt"
./qlogger/qlogger.manifest:    "homepage": "https://qt.gitorious.org/qtplayground/qlogger",
./qlogger/qlogger.manifest:    "vcs": "https://qt.gitorious.org/qtplayground/qlogger"
./qcustomplot/qcustomplot.2013-09-05.manifest:    "vcs": "https://gitorious.org/qcustomplot/",
./packagekit-qt/packagekit-qt.2013-05-08.manifest:    "vcs": "http://gitorious.org/packagekit/packagekit/trees/master/lib/packagekit-qt",
./packagekit-qt/packagekit-qt.2011-05-04.manifest:    "vcs": "http://gitorious.org/packagekit/packagekit/trees/master/lib/packagekit-qt"
./qserialdevice/qserialdevice.manifest:    "homepage": "https://gitorious.org/qserialdevice",
./qserialdevice/qserialdevice.manifest:    "vcs": "https://gitorious.org/qserialdevice/qserialdevice"
./cutelyst/cutelyst.2014-11-24.manifest:    "vcs": "https://gitorious.org/cutelyst/cutelyst.git",
./cutelyst/cutelyst.2014-11-24.manifest:    "source": "https://gitorious.org/cutelyst/cutelyst/archive/c77510285823c87b20726e40cda1ec7247d91966.tar.gz"
```

**Comment by cornelius** [comment]
Thanks for keeping track.

The URLs in old releases are fine, I think. That's where the code was developed. It's mostly history.

For others it would be good to keep something meaningful. Will the Gitorious URLs stop working or will they just be read-only?

**Comment by ibatullin** [comment]
Yes, Gitorious URLs will stop working. From GitLab post https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/:
> Gitorious.org will stay online until the end of May 2015 to give people time to migrate their repositories. 

What if old release of a project is available by new URL? 

If I looking for Qt 4 I will try to open broken http://qt.gitorious.org/qt from manifest of Qt 4 release. And I will find 404 error only. But the library will still be available at http://code.qt.io/cgit/qt/qt.git/

Should we keep all links valid or save project history? What you think?

**Comment by cornelius** [comment]
If URLs for old releases change and are available under new URLs I would update the old manifests. I think the part of the history we want to preserve is access to old versions, if available, not under which URL it was initially released.

For releases, where there is no new URL available I would keep the old one, though.

**Pull request merged**
