### PR TITLE
Updating to release manifest

### PR DESCRIPTION
**Pull request by andibacher**
As you suggested I changed the manifest to use the release manifest schema, aswe have a release now.

### CODE REVIEW

**Comment by cornelius** [comment]
Thanks for adapting the manifest. There is still one small change needed: The convention we use for the `name` attribute is to make it all lower-case to make processing easier. A properly capitalized name can be added as `display_name` attribute.

**Comment by andibacher** [comment]
I changed the name attribute and the manifest filename to lower case now.

**Comment by cornelius** [comment]
The name in the manifest needs to match the directory name, otherwise it doesn't work as a unique identifier and lookup of the manifest fails. So it should stay `log4qt-fork`.

**Comment by andibacher** [comment]
Ok. Do I also have to change the manifest filename? 
log4qt.2016-05-03.manifest  -> log4qt-fork.2016-05-03.manifest ?

**Comment by cornelius** [comment]
Yes, name attribute, file base name, and directory name all have to be the same.

**Pull request merged**
