### PR TITLE
Update to Cutelyst 1.0.0

### PR DESCRIPTION
**Pull request by dantti**

### CODE REVIEW

**Comment by nanduni-nin** [comment]
The check seems to fail because this manifest needs to be named as '**cutelyst.2016-11-10.manifest**' instead of '**cutelyst.2014-11-24.manifest**'.  It would be nice to have a separate manifest file with the name '**cutelyst.2016-11-10.manifest**' for the new release.

**Comment by dantti** [comment]
updated patch, still odd to have stuff in git if files are needed to track changes manually

**Comment by dantti** [comment]
@cornelius ping?

**Comment by cornelius** [comment]
Thanks for fixing it. I'll merge it now.

**Pull request merged**
