### PR TITLE
Add topics to manifests

### PR DESCRIPTION
**Pull request by nanduni-nin**
Use https://github.com/cornelius/inqlude/blob/master/topics/topics.csv as a base.
Topics are used to categorize libraries. Each library has one or more topics.

### CODE REVIEW

**Comment by cornelius** [comment]
Better not put the URL in the commit log. It might not be valid anymore at some point in the future, but the history with the commit message will be there forever.

**Comment by cornelius** [comment]
When running the verifier there are still 1580 warnings. I suppose these are older versions of the manifest. It would be good to get rid of them, so that it's feasible to actually look at the warnings and use them as indication that a manifest needs to be improved.

We could do this either by adding topics to all manifest, also the older ones, or by improving the validator to only check the topics on the latest manifest. Or do you have another idea for how to do it?

**Comment by nanduni-nin** [comment]
I think it would be better to add the topics to all manifests icluding the older ones.

**Comment by cornelius** [comment]
@nanduni-nin ok, sounds good

**Pull request closed without merging**
