### PR TITLE
Introduce QtFirebase project

### PR DESCRIPTION
**Pull request by Larpon**
Introduce the QtFirebase project.

QtFirebase is a wrap around the Firebase C++ API for Qt C++ & QML

### CODE REVIEW

**Comment by chehrlic** [comment]
Can you please fix the manifest file so I can merge this pull request?

**Comment by Larpon** [comment]
I'm on it

**Comment by cornelius** [comment]
Sorry, I was too quick. I had to revert the merge.

Could you please recreate the pull request with one commit adding the qtfirebase manifest and make sure that you have a valid name and email address in the commit?

**Comment by Larpon** [comment]
Nah. I just realised via the [platforms](https://github.com/cornelius/inqlude/blob/master/manifest-format.md#platforms) list - that it's only for desktops. QtFirebase is for iOS and Android. So I'll just leave it un-merged :)

**Comment by cornelius** [comment]
The platforms list documentation is outdated. We do list libraries for Android and iOS as well. I updated the documentation now.

**Comment by Larpon** [comment]
@cornelius - I'm not sure what you meant by "valid name and email address in the commit" - I can't find examples of an `email` entry in the manifest files - where do I add the email?

**Comment by cornelius** [comment]
It's not in the manifest but in the git commit. Use for example `git log` to see what name and email address you used to commit.

**Pull request merged**
