### PR TITLE
Update to Cutelyst 1.8.0

### PR DESCRIPTION
**Pull request by dantti**

### CODE REVIEW

**Comment by dantti** [comment]
Ping

**Comment by dantti** [comment]
@cornelius ping

**Comment by chehrlic** [comment]
Since cornelius has no time atm I pushed this commit to the kde git repo: https://inqlude.org/libraries/cutelyst.html
The github mirror is not synced - don't know why

**Comment by cornelius** [comment]
Closing this pull request. The data is in.

**Pull request closed without merging**
